export const fieldNames = {
  FULL_NAME: 'fullName',
  PHONE_NUMBER: 'phoneNumber',
  EMAIL: 'email',
  EMERGENCY_NUMBER_ONE: 'emergencyNumberOne',
  EMERGENCY_NUMBER_TWO: 'emergencyNumberTwo',
  PASSWORD: 'password',
  CONFIRM_PASSWORD: 'confirmPassword',
  PHONE: 'Phone',
  VEHICLE_NAME: 'vehicleName',
  VEHICLE_TYPE: 'vehicleType',
  VEHICLE_MODEL: 'vehicleModel',
  VEHICLE_REGISTRATION_NUMBER: 'vehicleRegistrationNumber',
  VEHICLE_SEATING_CAPACITY: 'vehicleSeatingCapacity',
  BUSINESS_DETAILS_NAME: 'businessName',
  BUSINESS_DETAILS_ADDRESS: 'businessAddress',
  BUSINESS_DETAILS_AREA: 'businessArea',
  BUSINESS_DETAILS_CITY: 'businessCity',
  BUSINESS_DETAILS_STATE: 'businessState',
};
